// default package
// Generated Oct 4, 2017 4:00:00 PM by Hibernate Tools 5.2.1.Final
package com.nic.projectproposal.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * PhysicalTargetTrngwiseTargets generated by hbm2java
 */
@Entity
@Table(name = "physical_target_trngwise_targets", schema = "public")
public class PhysicalTargetTrngwiseTargets implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8114874994128575536L;
	
	private Integer trngwiseTargetsId;
	private String statecode;
	private String distcode;
	private Integer target;

	@Id
	@Column(name = "trngwise_targets_id")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "physical_target_trngwise_targets_trngwise_targets_id_seq")
	@SequenceGenerator(name = "physical_target_trngwise_targets_trngwise_targets_id_seq", sequenceName = "physical_target_trngwise_targets_trngwise_targets_id_seq", allocationSize = 1)
   public Integer getTrngwiseTargetsId() {
		return trngwiseTargetsId;
	}

	public void setTrngwiseTargetsId(Integer trngwiseTargetsId) {
		this.trngwiseTargetsId = trngwiseTargetsId;
	}

	
	private PhysicalTarget physicalTarget;
	
	
	@ManyToOne
	@JoinColumn(name = "physicaltarget_id")
	public PhysicalTarget getPhysicalTarget() {
		return physicalTarget;
	}

	public void setPhysicalTarget(PhysicalTarget physicalTarget) {
		this.physicalTarget = physicalTarget;
	}

	

	@Column(name = "statecode")
	public String getStatecode() {
		return this.statecode;
	}

	public void setStatecode(String statecode) {
		this.statecode = statecode;
	}

	@Column(name = "distcode")
	public String getDistcode() {
		return this.distcode;
	}

	public void setDistcode(String distcode) {
		this.distcode = distcode;
	}
   
	@Column(name = "target_test")
	public Integer getTarget() {
		return this.target;
	}

	public void setTarget(Integer target) {
		this.target = target;
	}
	

}