package com.nic.projectproposal.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * PpGeneralDetails generated by hbm2java
 */
@Entity
@Table(name="pp_general_details"
    ,schema="public"
)
public class PpGeneralDetails  implements java.io.Serializable {


     private int projectProposalId;
     private String orgcode;
     private String proposalType;
     private String prnNumber;
     private String applyingAs;
     private String prnOfConsortiumMember;
     private String indicateLeadPartner;
     private String roleId;
     private String createdBy;
     private String modifiedBy;
     private Date createdDate;
     private Date modifiedDate;

    public PpGeneralDetails() {
    }

	
    public PpGeneralDetails(int projectProposalId) {
        this.projectProposalId = projectProposalId;
    }
    public PpGeneralDetails(int projectProposalId, String orgcode, String proposalType, String prnNumber, String applyingAs, String prnOfConsortiumMember, String indicateLeadPartner, String roleId, String createdBy, String modifiedBy, Date createdDate, Date modifiedDate) {
       this.projectProposalId = projectProposalId;
       this.orgcode = orgcode;
       this.proposalType = proposalType;
       this.prnNumber = prnNumber;
       this.applyingAs = applyingAs;
       this.prnOfConsortiumMember = prnOfConsortiumMember;
       this.indicateLeadPartner = indicateLeadPartner;
       this.roleId = roleId;
       this.createdBy = createdBy;
       this.modifiedBy = modifiedBy;
       this.createdDate = createdDate;
       this.modifiedDate = modifiedDate;
    }
   
  

		@Id
		@Column(name="project_proposal_id")
		@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="pp_general_details_project_proposal_id_seq")
		@SequenceGenerator(name="pp_general_details_project_proposal_id_seq", sequenceName="pp_general_details_project_proposal_id_seq", allocationSize=1)
		
    public int getProjectProposalId() {
        return this.projectProposalId;
    }
    
    public void setProjectProposalId(int projectProposalId) {
        this.projectProposalId = projectProposalId;
    }

    
    @Column(name="orgcode")
    @Transient
    public String getOrgcode() {
        return this.orgcode;
    }
    
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    
    @Column(name="proposal_type")
    public String getProposalType() {
        return this.proposalType;
    }
    
    public void setProposalType(String proposalType) {
        this.proposalType = proposalType;
    }

    
    @Column(name="prn_number")
    @Transient
    public String getPrnNumber() {
        return this.prnNumber;
    }
    
    public void setPrnNumber(String prnNumber) {
        this.prnNumber = prnNumber;
    }

    
    @Column(name="applying_as")
    public String getApplyingAs() {
        return this.applyingAs;
    }
    
    public void setApplyingAs(String applyingAs) {
        this.applyingAs = applyingAs;
    }

    
    @Column(name="prn_of_consortium_member")
    public String getPrnOfConsortiumMember() {
        return this.prnOfConsortiumMember;
    }
    
    public void setPrnOfConsortiumMember(String prnOfConsortiumMember) {
        this.prnOfConsortiumMember = prnOfConsortiumMember;
    }

    
    @Column(name="indicate_lead_partner")
    public String getIndicateLeadPartner() {
        return this.indicateLeadPartner;
    }
    
    public void setIndicateLeadPartner(String indicateLeadPartner) {
        this.indicateLeadPartner = indicateLeadPartner;
    }

    
    @Column(name="role_id")
    @Transient
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="created_by")
    @Transient
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    
    @Column(name="modified_by")
    @Transient
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="created_date", length=13)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="modified_date", length=13)
    @Transient
    public Date getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }




}


