// default package
// Generated Oct 7, 2017 2:06:52 PM by Hibernate Tools 5.2.1.Final
package com.nic.projectproposal.model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProposedLocationTrainingCenterId generated by hbm2java
 */
@Embeddable
public class ProposedLocationTrainingCenterId implements java.io.Serializable {

	private int proplocTraincenterId;
	private Integer physicaltargetId;
	private String statecode;
	private String distcode;
	private String specialarea;
	private Integer nooftrainingcenters;
	private String natureoftrainingcenter;
	private Integer proposedtrainingtarget;
	private String modifiedBy;
	private Date modifiedDate;
	private Date ts;
	private String ipaddress;
	private String roleId;
	private Date fromdt;
	private Date todate;
	private Integer targetTest;

	public ProposedLocationTrainingCenterId() {
	}

	public ProposedLocationTrainingCenterId(int proplocTraincenterId) {
		this.proplocTraincenterId = proplocTraincenterId;
	}

	public ProposedLocationTrainingCenterId(int proplocTraincenterId, Integer physicaltargetId, String statecode,
			String distcode, String specialarea, Integer nooftrainingcenters, String natureoftrainingcenter,
			Integer proposedtrainingtarget, String modifiedBy, Date modifiedDate, Date ts, String ipaddress,
			String roleId, Date fromdt, Date todate, Integer targetTest) {
		this.proplocTraincenterId = proplocTraincenterId;
		this.physicaltargetId = physicaltargetId;
		this.statecode = statecode;
		this.distcode = distcode;
		this.specialarea = specialarea;
		this.nooftrainingcenters = nooftrainingcenters;
		this.natureoftrainingcenter = natureoftrainingcenter;
		this.proposedtrainingtarget = proposedtrainingtarget;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.ts = ts;
		this.ipaddress = ipaddress;
		this.roleId = roleId;
		this.fromdt = fromdt;
		this.todate = todate;
		this.targetTest = targetTest;
	}

	@Column(name = "proploc_traincenter_id", nullable = false)
	public int getProplocTraincenterId() {
		return this.proplocTraincenterId;
	}

	public void setProplocTraincenterId(int proplocTraincenterId) {
		this.proplocTraincenterId = proplocTraincenterId;
	}

	@Column(name = "physicaltarget_id")
	public Integer getPhysicaltargetId() {
		return this.physicaltargetId;
	}

	public void setPhysicaltargetId(Integer physicaltargetId) {
		this.physicaltargetId = physicaltargetId;
	}

	@Column(name = "statecode")
	public String getStatecode() {
		return this.statecode;
	}

	public void setStatecode(String statecode) {
		this.statecode = statecode;
	}

	@Column(name = "distcode")
	public String getDistcode() {
		return this.distcode;
	}

	public void setDistcode(String distcode) {
		this.distcode = distcode;
	}

	@Column(name = "specialarea")
	public String getSpecialarea() {
		return this.specialarea;
	}

	public void setSpecialarea(String specialarea) {
		this.specialarea = specialarea;
	}

	@Column(name = "nooftrainingcenters")
	public Integer getNooftrainingcenters() {
		return this.nooftrainingcenters;
	}

	public void setNooftrainingcenters(Integer nooftrainingcenters) {
		this.nooftrainingcenters = nooftrainingcenters;
	}

	@Column(name = "natureoftrainingcenter")
	public String getNatureoftrainingcenter() {
		return this.natureoftrainingcenter;
	}

	public void setNatureoftrainingcenter(String natureoftrainingcenter) {
		this.natureoftrainingcenter = natureoftrainingcenter;
	}

	@Column(name = "proposedtrainingtarget")
	public Integer getProposedtrainingtarget() {
		return this.proposedtrainingtarget;
	}

	public void setProposedtrainingtarget(Integer proposedtrainingtarget) {
		this.proposedtrainingtarget = proposedtrainingtarget;
	}

	@Column(name = "modified_by")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modified_date", length = 13)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "ts", length = 29)
	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	@Column(name = "ipaddress")
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "role_id")
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "fromdt", length = 13)
	public Date getFromdt() {
		return this.fromdt;
	}

	public void setFromdt(Date fromdt) {
		this.fromdt = fromdt;
	}

	@Column(name = "todate", length = 13)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "target_test")
	public Integer getTargetTest() {
		return this.targetTest;
	}

	public void setTargetTest(Integer targetTest) {
		this.targetTest = targetTest;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProposedLocationTrainingCenterId))
			return false;
		ProposedLocationTrainingCenterId castOther = (ProposedLocationTrainingCenterId) other;

		return (this.getProplocTraincenterId() == castOther.getProplocTraincenterId())
				&& ((this.getPhysicaltargetId() == castOther.getPhysicaltargetId())
						|| (this.getPhysicaltargetId() != null && castOther.getPhysicaltargetId() != null
								&& this.getPhysicaltargetId().equals(castOther.getPhysicaltargetId())))
				&& ((this.getStatecode() == castOther.getStatecode()) || (this.getStatecode() != null
						&& castOther.getStatecode() != null && this.getStatecode().equals(castOther.getStatecode())))
				&& ((this.getDistcode() == castOther.getDistcode()) || (this.getDistcode() != null
						&& castOther.getDistcode() != null && this.getDistcode().equals(castOther.getDistcode())))
				&& ((this.getSpecialarea() == castOther.getSpecialarea())
						|| (this.getSpecialarea() != null && castOther.getSpecialarea() != null
								&& this.getSpecialarea().equals(castOther.getSpecialarea())))
				&& ((this.getNooftrainingcenters() == castOther.getNooftrainingcenters())
						|| (this.getNooftrainingcenters() != null && castOther.getNooftrainingcenters() != null
								&& this.getNooftrainingcenters().equals(castOther.getNooftrainingcenters())))
				&& ((this.getNatureoftrainingcenter() == castOther.getNatureoftrainingcenter())
						|| (this.getNatureoftrainingcenter() != null && castOther.getNatureoftrainingcenter() != null
								&& this.getNatureoftrainingcenter().equals(castOther.getNatureoftrainingcenter())))
				&& ((this.getProposedtrainingtarget() == castOther.getProposedtrainingtarget())
						|| (this.getProposedtrainingtarget() != null && castOther.getProposedtrainingtarget() != null
								&& this.getProposedtrainingtarget().equals(castOther.getProposedtrainingtarget())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedDate() == castOther.getModifiedDate())
						|| (this.getModifiedDate() != null && castOther.getModifiedDate() != null
								&& this.getModifiedDate().equals(castOther.getModifiedDate())))
				&& ((this.getTs() == castOther.getTs()) || (this.getTs() != null && castOther.getTs() != null
						&& this.getTs().equals(castOther.getTs())))
				&& ((this.getIpaddress() == castOther.getIpaddress()) || (this.getIpaddress() != null
						&& castOther.getIpaddress() != null && this.getIpaddress().equals(castOther.getIpaddress())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
						&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getFromdt() == castOther.getFromdt()) || (this.getFromdt() != null
						&& castOther.getFromdt() != null && this.getFromdt().equals(castOther.getFromdt())))
				&& ((this.getTodate() == castOther.getTodate()) || (this.getTodate() != null
						&& castOther.getTodate() != null && this.getTodate().equals(castOther.getTodate())))
				&& ((this.getTargetTest() == castOther.getTargetTest())
						|| (this.getTargetTest() != null && castOther.getTargetTest() != null
								&& this.getTargetTest().equals(castOther.getTargetTest())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProplocTraincenterId();
		result = 37 * result + (getPhysicaltargetId() == null ? 0 : this.getPhysicaltargetId().hashCode());
		result = 37 * result + (getStatecode() == null ? 0 : this.getStatecode().hashCode());
		result = 37 * result + (getDistcode() == null ? 0 : this.getDistcode().hashCode());
		result = 37 * result + (getSpecialarea() == null ? 0 : this.getSpecialarea().hashCode());
		result = 37 * result + (getNooftrainingcenters() == null ? 0 : this.getNooftrainingcenters().hashCode());
		result = 37 * result + (getNatureoftrainingcenter() == null ? 0 : this.getNatureoftrainingcenter().hashCode());
		result = 37 * result + (getProposedtrainingtarget() == null ? 0 : this.getProposedtrainingtarget().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode());
		result = 37 * result + (getTs() == null ? 0 : this.getTs().hashCode());
		result = 37 * result + (getIpaddress() == null ? 0 : this.getIpaddress().hashCode());
		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getFromdt() == null ? 0 : this.getFromdt().hashCode());
		result = 37 * result + (getTodate() == null ? 0 : this.getTodate().hashCode());
		result = 37 * result + (getTargetTest() == null ? 0 : this.getTargetTest().hashCode());
		return result;
	}

}
