// default package
// Generated Oct 7, 2017 2:06:52 PM by Hibernate Tools 5.2.1.Final
package com.nic.projectproposal.model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProposedTradewiseTargetsId generated by hbm2java
 */
@Embeddable
public class ProposedTradewiseTargetsId implements java.io.Serializable {

	private int propTradewiseTargetId;
	private Integer physicaltargetId;
	private String sector;
	private String trade;
	private String tradecode;
	private Integer domainTrainingHrs;
	private String costCategory;
	private String certifyingAgency;
	private Integer targetCandidates;
	private String prerequisiteTrades;
	private Integer totalTradeTrainingDuration;
	private Integer classroomHrs;
	private Integer ojtHrs;
	private Integer tradeWiseTarget;
	private String modifiedBy;
	private Date modifiedDate;
	private Date ts;
	private String ipaddress;
	private String roleId;
	private Date fromdt;
	private Date todate;
	private Integer targetTest;

	public ProposedTradewiseTargetsId() {
	}

	public ProposedTradewiseTargetsId(int propTradewiseTargetId) {
		this.propTradewiseTargetId = propTradewiseTargetId;
	}

	public ProposedTradewiseTargetsId(int propTradewiseTargetId, Integer physicaltargetId, String sector, String trade,
			String tradecode, Integer domainTrainingHrs, String costCategory, String certifyingAgency,
			Integer targetCandidates, String prerequisiteTrades, Integer totalTradeTrainingDuration,
			Integer classroomHrs, Integer ojtHrs, Integer tradeWiseTarget, String modifiedBy, Date modifiedDate,
			Date ts, String ipaddress, String roleId, Date fromdt, Date todate, Integer targetTest) {
		this.propTradewiseTargetId = propTradewiseTargetId;
		this.physicaltargetId = physicaltargetId;
		this.sector = sector;
		this.trade = trade;
		this.tradecode = tradecode;
		this.domainTrainingHrs = domainTrainingHrs;
		this.costCategory = costCategory;
		this.certifyingAgency = certifyingAgency;
		this.targetCandidates = targetCandidates;
		this.prerequisiteTrades = prerequisiteTrades;
		this.totalTradeTrainingDuration = totalTradeTrainingDuration;
		this.classroomHrs = classroomHrs;
		this.ojtHrs = ojtHrs;
		this.tradeWiseTarget = tradeWiseTarget;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.ts = ts;
		this.ipaddress = ipaddress;
		this.roleId = roleId;
		this.fromdt = fromdt;
		this.todate = todate;
		this.targetTest = targetTest;
	}

	@Column(name = "prop_tradewise_target_id", nullable = false)
	public int getPropTradewiseTargetId() {
		return this.propTradewiseTargetId;
	}

	public void setPropTradewiseTargetId(int propTradewiseTargetId) {
		this.propTradewiseTargetId = propTradewiseTargetId;
	}

	@Column(name = "physicaltarget_id")
	public Integer getPhysicaltargetId() {
		return this.physicaltargetId;
	}

	public void setPhysicaltargetId(Integer physicaltargetId) {
		this.physicaltargetId = physicaltargetId;
	}

	@Column(name = "sector")
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "trade")
	public String getTrade() {
		return this.trade;
	}

	public void setTrade(String trade) {
		this.trade = trade;
	}

	@Column(name = "tradecode")
	public String getTradecode() {
		return this.tradecode;
	}

	public void setTradecode(String tradecode) {
		this.tradecode = tradecode;
	}

	@Column(name = "domain_training_hrs")
	public Integer getDomainTrainingHrs() {
		return this.domainTrainingHrs;
	}

	public void setDomainTrainingHrs(Integer domainTrainingHrs) {
		this.domainTrainingHrs = domainTrainingHrs;
	}

	@Column(name = "cost_category")
	public String getCostCategory() {
		return this.costCategory;
	}

	public void setCostCategory(String costCategory) {
		this.costCategory = costCategory;
	}

	@Column(name = "certifying_agency")
	public String getCertifyingAgency() {
		return this.certifyingAgency;
	}

	public void setCertifyingAgency(String certifyingAgency) {
		this.certifyingAgency = certifyingAgency;
	}

	@Column(name = "target_candidates")
	public Integer getTargetCandidates() {
		return this.targetCandidates;
	}

	public void setTargetCandidates(Integer targetCandidates) {
		this.targetCandidates = targetCandidates;
	}

	@Column(name = "prerequisite_trades")
	public String getPrerequisiteTrades() {
		return this.prerequisiteTrades;
	}

	public void setPrerequisiteTrades(String prerequisiteTrades) {
		this.prerequisiteTrades = prerequisiteTrades;
	}

	@Column(name = "total_trade_training_duration")
	public Integer getTotalTradeTrainingDuration() {
		return this.totalTradeTrainingDuration;
	}

	public void setTotalTradeTrainingDuration(Integer totalTradeTrainingDuration) {
		this.totalTradeTrainingDuration = totalTradeTrainingDuration;
	}

	@Column(name = "classroom_hrs")
	public Integer getClassroomHrs() {
		return this.classroomHrs;
	}

	public void setClassroomHrs(Integer classroomHrs) {
		this.classroomHrs = classroomHrs;
	}

	@Column(name = "ojt_hrs")
	public Integer getOjtHrs() {
		return this.ojtHrs;
	}

	public void setOjtHrs(Integer ojtHrs) {
		this.ojtHrs = ojtHrs;
	}

	@Column(name = "trade_wise_target")
	public Integer getTradeWiseTarget() {
		return this.tradeWiseTarget;
	}

	public void setTradeWiseTarget(Integer tradeWiseTarget) {
		this.tradeWiseTarget = tradeWiseTarget;
	}

	@Column(name = "modified_by")
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modified_date", length = 13)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "ts", length = 29)
	public Date getTs() {
		return this.ts;
	}

	public void setTs(Date ts) {
		this.ts = ts;
	}

	@Column(name = "ipaddress")
	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	@Column(name = "role_id")
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "fromdt", length = 13)
	public Date getFromdt() {
		return this.fromdt;
	}

	public void setFromdt(Date fromdt) {
		this.fromdt = fromdt;
	}

	@Column(name = "todate", length = 13)
	public Date getTodate() {
		return this.todate;
	}

	public void setTodate(Date todate) {
		this.todate = todate;
	}

	@Column(name = "target_test")
	public Integer getTargetTest() {
		return this.targetTest;
	}

	public void setTargetTest(Integer targetTest) {
		this.targetTest = targetTest;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProposedTradewiseTargetsId))
			return false;
		ProposedTradewiseTargetsId castOther = (ProposedTradewiseTargetsId) other;

		return (this.getPropTradewiseTargetId() == castOther.getPropTradewiseTargetId())
				&& ((this.getPhysicaltargetId() == castOther.getPhysicaltargetId())
						|| (this.getPhysicaltargetId() != null && castOther.getPhysicaltargetId() != null
								&& this.getPhysicaltargetId().equals(castOther.getPhysicaltargetId())))
				&& ((this.getSector() == castOther.getSector()) || (this.getSector() != null
						&& castOther.getSector() != null && this.getSector().equals(castOther.getSector())))
				&& ((this.getTrade() == castOther.getTrade()) || (this.getTrade() != null
						&& castOther.getTrade() != null && this.getTrade().equals(castOther.getTrade())))
				&& ((this.getTradecode() == castOther.getTradecode()) || (this.getTradecode() != null
						&& castOther.getTradecode() != null && this.getTradecode().equals(castOther.getTradecode())))
				&& ((this.getDomainTrainingHrs() == castOther.getDomainTrainingHrs())
						|| (this.getDomainTrainingHrs() != null && castOther.getDomainTrainingHrs() != null
								&& this.getDomainTrainingHrs().equals(castOther.getDomainTrainingHrs())))
				&& ((this.getCostCategory() == castOther.getCostCategory())
						|| (this.getCostCategory() != null && castOther.getCostCategory() != null
								&& this.getCostCategory().equals(castOther.getCostCategory())))
				&& ((this.getCertifyingAgency() == castOther.getCertifyingAgency())
						|| (this.getCertifyingAgency() != null && castOther.getCertifyingAgency() != null
								&& this.getCertifyingAgency().equals(castOther.getCertifyingAgency())))
				&& ((this.getTargetCandidates() == castOther.getTargetCandidates())
						|| (this.getTargetCandidates() != null && castOther.getTargetCandidates() != null
								&& this.getTargetCandidates().equals(castOther.getTargetCandidates())))
				&& ((this.getPrerequisiteTrades() == castOther.getPrerequisiteTrades())
						|| (this.getPrerequisiteTrades() != null && castOther.getPrerequisiteTrades() != null
								&& this.getPrerequisiteTrades().equals(castOther.getPrerequisiteTrades())))
				&& ((this.getTotalTradeTrainingDuration() == castOther.getTotalTradeTrainingDuration())
						|| (this.getTotalTradeTrainingDuration() != null
								&& castOther.getTotalTradeTrainingDuration() != null
								&& this.getTotalTradeTrainingDuration()
										.equals(castOther.getTotalTradeTrainingDuration())))
				&& ((this.getClassroomHrs() == castOther.getClassroomHrs())
						|| (this.getClassroomHrs() != null && castOther.getClassroomHrs() != null
								&& this.getClassroomHrs().equals(castOther.getClassroomHrs())))
				&& ((this.getOjtHrs() == castOther.getOjtHrs()) || (this.getOjtHrs() != null
						&& castOther.getOjtHrs() != null && this.getOjtHrs().equals(castOther.getOjtHrs())))
				&& ((this.getTradeWiseTarget() == castOther.getTradeWiseTarget())
						|| (this.getTradeWiseTarget() != null && castOther.getTradeWiseTarget() != null
								&& this.getTradeWiseTarget().equals(castOther.getTradeWiseTarget())))
				&& ((this.getModifiedBy() == castOther.getModifiedBy()) || (this.getModifiedBy() != null
						&& castOther.getModifiedBy() != null && this.getModifiedBy().equals(castOther.getModifiedBy())))
				&& ((this.getModifiedDate() == castOther.getModifiedDate())
						|| (this.getModifiedDate() != null && castOther.getModifiedDate() != null
								&& this.getModifiedDate().equals(castOther.getModifiedDate())))
				&& ((this.getTs() == castOther.getTs()) || (this.getTs() != null && castOther.getTs() != null
						&& this.getTs().equals(castOther.getTs())))
				&& ((this.getIpaddress() == castOther.getIpaddress()) || (this.getIpaddress() != null
						&& castOther.getIpaddress() != null && this.getIpaddress().equals(castOther.getIpaddress())))
				&& ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
						&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getFromdt() == castOther.getFromdt()) || (this.getFromdt() != null
						&& castOther.getFromdt() != null && this.getFromdt().equals(castOther.getFromdt())))
				&& ((this.getTodate() == castOther.getTodate()) || (this.getTodate() != null
						&& castOther.getTodate() != null && this.getTodate().equals(castOther.getTodate())))
				&& ((this.getTargetTest() == castOther.getTargetTest())
						|| (this.getTargetTest() != null && castOther.getTargetTest() != null
								&& this.getTargetTest().equals(castOther.getTargetTest())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPropTradewiseTargetId();
		result = 37 * result + (getPhysicaltargetId() == null ? 0 : this.getPhysicaltargetId().hashCode());
		result = 37 * result + (getSector() == null ? 0 : this.getSector().hashCode());
		result = 37 * result + (getTrade() == null ? 0 : this.getTrade().hashCode());
		result = 37 * result + (getTradecode() == null ? 0 : this.getTradecode().hashCode());
		result = 37 * result + (getDomainTrainingHrs() == null ? 0 : this.getDomainTrainingHrs().hashCode());
		result = 37 * result + (getCostCategory() == null ? 0 : this.getCostCategory().hashCode());
		result = 37 * result + (getCertifyingAgency() == null ? 0 : this.getCertifyingAgency().hashCode());
		result = 37 * result + (getTargetCandidates() == null ? 0 : this.getTargetCandidates().hashCode());
		result = 37 * result + (getPrerequisiteTrades() == null ? 0 : this.getPrerequisiteTrades().hashCode());
		result = 37 * result
				+ (getTotalTradeTrainingDuration() == null ? 0 : this.getTotalTradeTrainingDuration().hashCode());
		result = 37 * result + (getClassroomHrs() == null ? 0 : this.getClassroomHrs().hashCode());
		result = 37 * result + (getOjtHrs() == null ? 0 : this.getOjtHrs().hashCode());
		result = 37 * result + (getTradeWiseTarget() == null ? 0 : this.getTradeWiseTarget().hashCode());
		result = 37 * result + (getModifiedBy() == null ? 0 : this.getModifiedBy().hashCode());
		result = 37 * result + (getModifiedDate() == null ? 0 : this.getModifiedDate().hashCode());
		result = 37 * result + (getTs() == null ? 0 : this.getTs().hashCode());
		result = 37 * result + (getIpaddress() == null ? 0 : this.getIpaddress().hashCode());
		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getFromdt() == null ? 0 : this.getFromdt().hashCode());
		result = 37 * result + (getTodate() == null ? 0 : this.getTodate().hashCode());
		result = 37 * result + (getTargetTest() == null ? 0 : this.getTargetTest().hashCode());
		return result;
	}

}
